### ISSUE TITLE
Axis ordering for yandasoft related tasks

### ISSUE THREAD

**Issue by tjgalvin** [AlecThomson/fitscube#9]
The yandasoft linmos (and perhaps linmos-mp) tasks want to have the axis order as `(chan, pol, dec, ra)`. Perhaps there should be an option to for the fits cubes in this order as they are being created. It could avoid needing to reread and temporarily increase disk space  when reordering, which would be advantageous as we move to larger cubes.

**Comment by AlecThomson** [comment]
I recently become away of `imageaccess.axis` option in [linmos](https://yandasoft.readthedocs.io/en/latest/calim/linmos.html). That option should solve the issue.
